spring:
  config:
    activate:
      on-profile: test
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service-test:8081
          predicates:
            - Path=/api/auth/**,/api/users/**
        - id: customer-service
          uri: http://customer-service-test:8082
          predicates:
            - Path=/api/customers/**,/api/kyc/**
        - id: account-service
          uri: http://account-service-test:8083
          predicates:
            - Path=/api/accounts/**,/api/transactions/**
